### ISSUE TITLE
Blazor WebApp .NET 8

### ISSUE THREAD

**Issue by LunaWanderer1** [xaviersolau/BlazorJsonLocalization#54]
Hi, 

I'm trying to use this library with the new Blazor WebApp with the following configuration:

Server:
```
builder.Services.AddServerSideJsonLocalization(builder =>
{
    builder.UseEmbeddedJson(options =>
    {
        options.ResourcesPath = "Resources";
    });

    builder.EnableLogger(true);
});
```

WebAsssembly:

```
builder.Services.AddWebAssemblyJsonLocalization(localbuilder =>
{
    localbuilder.UseHttpHostedJson(options =>
    {
        options.ResourcesPath = "Resources";
        options.NamingPolicy = (basePath, cultureName) =>
        {
            return new Uri(
                $"{basePath.Replace("_content/Blazor.Client/", builder.HostEnvironment.BaseAddress)}.{cultureName}.json",
                UriKind.Absolute
            );
        };
    });
    localbuilder.EnableLogger(true);
});
```

I have both files Global.en-US.json and Global.fr-FR.json under the Server Project in wwwroot/Resources/.

I get the following errors:

warn: SoloX.BlazorJsonLocalization.Services.Impl.EmbeddedJsonLocalizationExtensionService[7]
      Embedded File Resources\Global.en-US.json does not exist
warn: SoloX.BlazorJsonLocalization.Services.Impl.EmbeddedJsonLocalizationExtensionService[7]
      Embedded File Resources\Global.en.json does not exist
warn: SoloX.BlazorJsonLocalization.Services.Impl.EmbeddedJsonLocalizationExtensionService[7]
      Embedded File Resources\Global.json does not exist
fail: SoloX.BlazorJsonLocalization.Core.Impl.JsonStringLocalizerFactory[14]
      Unable to load localization data for Blazor.Client.Global in assembly Blazor.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null with culture en-US

I've tried playing around with the file location. If I put them in the Client Project, then Server Mode works but WebAssembly mode stops working and I get the error:

"Failed to find a valid digest in the 'integrity' attribute for resource"

Any ideas?

**Comment by xaviersolau** [comment]
Hello,
What version of the library do you use?
Why do you use HttpHosted in client side and Embedded on server? Why don't you use same on both? its simpler if you use same on both. Otherwise you may need to do additional setup on server side. (There are examples in the repository where it is done)
* In the case where you want to use Embedded, your files must be in your project folder like this:
{poject folder}\Resources\Global.xx-XX.json
and make sure that the files are embedded in the assembly and that the satellite assembly are generated.
* When you want to use HttpHosted you have to put your files in your wwwroot:
{poject folder}\wwwroot\Resources\Global.xx-XX.json

If you use the version 2.0.0, you don't need to setup NamingPolicy, it is already define the way you name your files.

I will try to add an example using .Net 8.

Hope this helps, let me know.

**Comment by LunaWanderer1** [comment]
Hello,

I am using version 2.0.0. I was initially using Embedded Resource only but I wasn't getting any luck with it at all so started looking at other solutions.

Must be something wrong with my solution, will have to check on Monday but I created a quick example showing it working here:

https://github.com/LunaWanderer1/BlazorLocalization

Worked pretty much right away with just the Embedded files

**Comment by xaviersolau** [comment]
Yes I see, it's working fine with Embedded!

I have done the exercise to change it in order to work with Http hosted Json... (I can push a PR if you want....)
To make it work you need to do those steps:

* Add **SoloX.BlazorJsonLocalization.ServerSide** PackageReference in **Blazor**.csproj
* Add **SoloX.BlazorJsonLocalization.WebAssembly** PackageReference in **Blazor.Client**.csproj
* Move the `Resources/Global.xx-XX.json` files to the `wwwroot` in Blazor.Client project
* Remove the json file from EmbeddedResource in Blazor.Client.csproj
* In Program.cs (from Blazor project) change the AddJsonLocalization like this:
```
builder.Services.AddServerSideJsonLocalization(
    builder => builder
        .EnableLogger(true) // If you want to see the logs
        .UseHttpHostedJson(options =>
        {
            options.ResourcesPath = "Resources";
            options.ApplicationAssembly = typeof(Global).Assembly;
        }));
```
* In Program.cs (from Blazor.Client project) add HttpClient injection support:
```
builder.Services.AddScoped(sp =>
    new HttpClient
    {
        BaseAddress = new Uri(builder.HostEnvironment.BaseAddress)
    });
```
* In Program.cs (from Blazor.Client project) change the AddJsonLocalization like this:
```
builder.Services.AddWebAssemblyJsonLocalization(
    builder => builder
        .EnableLogger(true) // If you want to see the logs
        .UseHttpHostedJson(options =>
        {
            options.ResourcesPath = "Resources";
            options.ApplicationAssembly = typeof(Global).Assembly;
        }));
```
* And finally since this is asynchronous loading files you can also add in your _Imports.razor file (In Blazor.Client):
`@using SoloX.BlazorJsonLocalization
`
* And in Home.razor
```
    protected override async Task OnInitializedAsync()
    {
        await Loc.LoadAsync();
        await base.OnInitializedAsync();
    }

```

Hope this helps!
